version: '3.8'

services:
  merchandise-service:
    image: ${DOCKER_REGISTRY-}merchandise-service
    build:
      context: ../
      dockerfile: ./src/OzonEdu.MerchandiseService/Dockerfile
    hostname: merchandise-service
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5428;Database=merchandise-service;Username=postgres;Password=merchandiseServicePassword"
    ports:
      - "80:80"
    depends_on:
      - merchandise-service-db
      - supply-service
      - emailing-service
      - employees-service
      - stock-api

  merchandise-service-db:
    image: postgres:latest
    ports:
      - "5428:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merchandiseServicePassword
      POSTGRES_DB: merchandise-service
  
  supply-service:
    image: ghcr.io/ozon-edu-csharp-2021/supply-service:main
    environment:
      DbConfiguration__ConnectionString: "Host=host.docker.internal;Port=5426;Database=supply-service;Username=postgres;Password=supplyServicePassword"
    hostname: supply-service
    depends_on:
      - supply-service-db

  emailing-service:
    image: ghcr.io/ozon-edu-csharp-2021/emailing-service:main
    hostname: emailing-service

  employees-service:
    image: ghcr.io/ozon-edu-csharp-2021/employees-service:main
    hostname: employees-service
    depends_on:
      - employees-service-postgres-db
    volumes:
      - ./src:/src

  stock-api:
    image: ghcr.io/ozon-edu-csharp-2021/stock-api:main
    hostname: stock-api
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5427;Database=stock-api;Username=postgres;Password=stockApiPassword"
    depends_on:
      - stock-api-db

  supply-service-db:
    image: postgres:latest
    ports:
      - "5426:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supplyServicePassword
      POSTGRES_DB: supply-service

  employees-service-postgres-db:
    image: postgres:latest
    ports:
      - "5425:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees-service
    volumes:
      - ./db/employees-service-postgres-db/dbdata:/var/lib/postgresql/data"

  stock-api-db:
    image: postgres:latest
    ports:
      - "5427:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stockApiPassword
      POSTGRES_DB: stock-api