version: '3.8'

services:
  merchandise-service:
    image: ${DOCKER_REGISTRY-}merchandise-service
    build:
      context: ../
      dockerfile: ./src/OzonEdu.MerchandiseService/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - supply-service
      - emailing-service
      - employees-service
      - stock-api
  supply-service:
    image: "ghcr.io/ozon-edu-csharp-2021/supply-service:main"
  emailing-service:
    image: "ghcr.io/ozon-edu-csharp-2021/emailing-service:main"
  employees-service:
    image: "ghcr.io/ozon-edu-csharp-2021/employees-service:main"
  stock-api:
    image: "ghcr.io/ozon-edu-csharp-2021/stock-api:main"